const stock_comedor = [
    {
        id: "c01", 
        nombre: "Estantería Circular",
        sector: "Comedor", 
        categoria: "Adornos Comedor",
        descripcion: "Estantería de Diseño Circular ideal para tu comedor" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 22318, 
        img: "../../../images/productos/producto10adornopared.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "c02", 
        nombre: "Borlas para Sujetar Cortina",
        sector: "Comedor", 
        categoria: "Accesorios Varios",
        descripcion: "Borlas para sujetar cortinas. Se venden por par" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 1482, 
        img: "../../../images/productos/producto17borlascortina.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "c03", 
        nombre: "Camino de Mesa Tejido",
        sector: "Comedor", 
        categoria: "Caminos de Mesa",
        descripcion: "Camino de Mesa Tejido Rectangular de 2.10 mts" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 3568, 
        img: "../../../images/productos/producto25caminodemesa.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "c04", 
        nombre: "Lampara de mimbre",
        sector: "Comedor", 
        categoria: "Lamparas",
        descripcion: "Lampara de mimbre para comedor" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 24999, 
        img: "../../../images/productos/producto15lampara.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "c05", 
        nombre: "Estantería Circular",
        sector: "Comedor", 
        categoria: "Adornos Comedor",
        descripcion: "Estantería de Diseño Circular ideal para tu comedor" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 22318, 
        img: "../../../images/productos/producto10adornopared.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "c06", 
        nombre: "Borlas para Sujetar Cortina",
        sector: "Comedor", 
        categoria: "Accesorios Varios",
        descripcion: "Borlas para sujetar cortinas. Se venden por par" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 1482, 
        img: "../../../images/productos/producto17borlascortina.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "c07", 
        nombre: "Camino de Mesa Tejido",
        sector: "Comedor", 
        categoria: "Caminos de Mesa",
        descripcion: "Camino de Mesa Tejido Rectangular de 2.10 mts" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 3568, 
        img: "../../../images/productos/producto25caminodemesa.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "c08", 
        nombre: "Lampara de mimbre",
        sector: "Comedor", 
        categoria: "Lamparas",
        descripcion: "Lampara de mimbre para comedor" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 24999, 
        img: "../../../images/productos/producto15lampara.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "c09", 
        nombre: "Estantería Circular",
        sector: "Comedor", 
        categoria: "Adornos Comedor",
        descripcion: "Estantería de Diseño Circular ideal para tu comedor" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 22318, 
        img: "../../../images/productos/producto10adornopared.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "c10", 
        nombre: "Borlas para Sujetar Cortina",
        sector: "Comedor", 
        categoria: "Accesorios Varios",
        descripcion: "Borlas para sujetar cortinas. Se venden por par" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 1482, 
        img: "../../../images/productos/producto17borlascortina.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "c11", 
        nombre: "Camino de Mesa Tejido",
        sector: "Comedor", 
        categoria: "Caminos de Mesa",
        descripcion: "Camino de Mesa Tejido Rectangular de 2.10 mts" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 3568, 
        img: "../../../images/productos/producto25caminodemesa.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "c12", 
        nombre: "Lampara de mimbre",
        sector: "Comedor", 
        categoria: "Lamparas",
        descripcion: "Lampara de mimbre para comedor" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 24999, 
        img: "../../../images/productos/producto15lampara.jpg",
        cantidad: 1,
        stock: 12, 
    }, 
]

export {stock_comedor};