const stock_comedor = [
    {
        id: "c01", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "c02", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "c03", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "c04", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "c05", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "c06", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "c07", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "c08", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "c09", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "c10", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "c11", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "c12", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 
]

export {stock_comedor};