const stock_kitchen = [
    {
        id: "k01", 
        nombre: "Mantel de Cocina Lienzo",
        sector: "Cocina", 
        categoria: "Manteles",
        descripcion: "Mantel de Lienzo Rectangular" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 2147, 
        img: "../../../images/productos/producto16mantelcocina.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "k02", 
        nombre: "Repasador de Mickey",
        sector: "Cocina", 
        categoria: "Repasadores",
        descripcion: "Repasador de Algodon con Royalties de Disney" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 947, 
        img: "../../../images/productos/producto14repasador.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "k03", 
        nombre: "Mantel Antimanchas",
        sector: "Cocina", 
        categoria: "Manteles",
        descripcion: "Unico mantel antimanchas rectangular, ignifugo, antiarrugas" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147, 
        img: "../../../images/productos/producto03mantelcocina.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "k04", 
        nombre: "Delantal de Cocina Mickey",
        sector: "Cocina", 
        categoria: "Delantal",
        descripcion: "Delantal de Cocina con Royalties de Disney" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 15147, 
        img: "../../../images/productos/producto13delantal.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "k05", 
        nombre: "Mantel de Cocina Lienzo",
        sector: "Cocina", 
        categoria: "Manteles",
        descripcion: "Mantel de Lienzo Rectangular" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 2147, 
        img: "../../../images/productos/producto16mantelcocina.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "k06", 
        nombre: "Repasador de Mickey",
        sector: "Cocina", 
        categoria: "Repasadores",
        descripcion: "Repasador de Algodon con Royalties de Disney" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 947, 
        img: "../../../images/productos/producto14repasador.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "k07", 
        nombre: "Mantel Antimanchas",
        sector: "Cocina", 
        categoria: "Manteles",
        descripcion: "Unico mantel antimanchas rectangular, ignifugo, antiarrugas" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147, 
        img: "../../../images/productos/producto03mantelcocina.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "k08", 
        nombre: "Delantal de Cocina Mickey",
        sector: "Cocina", 
        categoria: "Delantal",
        descripcion: "Delantal de Cocina con Royalties de Disney" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 15147, 
        img: "../../../images/productos/producto13delantal.jpg",
        cantidad: 1,
        stock: 12 
    }, 

    {
        id: "k09", 
        nombre: "Mantel de Cocina Lienzo",
        sector: "Cocina", 
        categoria: "Manteles",
        descripcion: "Mantel de Lienzo Rectangular" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 2147, 
        img: "../../../images/productos/producto16mantelcocina.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "k10", 
        nombre: "Repasador de Mickey",
        sector: "Cocina", 
        categoria: "Repasadores",
        descripcion: "Repasador de Algodon con Royalties de Disney" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 947, 
        img: "../../../images/productos/producto14repasador.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "k11", 
        nombre: "Mantel Antimanchas",
        sector: "Cocina", 
        categoria: "Manteles",
        descripcion: "Unico mantel antimanchas rectangular, ignifugo, antiarrugas" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147, 
        img: "../../../images/productos/producto03mantelcocina.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "k12", 
        nombre: "Delantal de Cocina Mickey",
        sector: "Cocina", 
        categoria: "Delantal",
        descripcion: "Delantal de Cocina con Royalties de Disney" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 15147, 
        img: "../../../images/productos/producto13delantal.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

]

export {stock_kitchen};