const stock_bathroom = [
    {
        id: "b01", 
        nombre: "Cortinas para Baño con Forro Antihongos",
        sector: "Bathroom", 
        categoria: "Bañadera",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "b02", 
        nombre: "Cortinas para Baño con Forro Antihongos",
        sector: "Bathroom", 
        categoria: "Bañadera",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "b03", 
        nombre: "Cortinas para Baño con Forro Antihongos",
        sector: "Bathroom", 
        categoria: "Bañadera",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "b04", 
        nombre: "Cortinas para Baño con Forro Antihongos",
        sector: "Bathroom", 
        categoria: "Bañadera",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "b05", 
        nombre: "Cortinas para Baño con Forro Antihongos",
        sector: "Bathroom", 
        categoria: "Bañadera",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "b06", 
        nombre: "Cortinas para Baño con Forro Antihongos",
        sector: "Bathroom", 
        categoria: "Bañadera",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "b07", 
        nombre: "Cortinas para Baño con Forro Antihongos",
        sector: "Bathroom", 
        categoria: "Bañadera",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "b08", 
        nombre: "Cortinas para Baño con Forro Antihongos",
        sector: "Bathroom", 
        categoria: "Bañadera",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "b09", 
        nombre: "Cortinas para Baño con Forro Antihongos",
        sector: "Bathroom", 
        categoria: "Bañadera",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "b10", 
        nombre: "Cortinas para Baño con Forro Antihongos",
        sector: "Bathroom", 
        categoria: "Bañadera",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "b11", 
        nombre: "Cortinas para Baño con Forro Antihongos",
        sector: "Bathroom", 
        categoria: "Bañadera",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "b12", 
        nombre: "Cortinas para Baño con Forro Antihongos",
        sector: "Bathroom", 
        categoria: "Bañadera",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 12, 
    }, 
]

export {stock_bathroom};