const stock_garden = [
    {
        id: "g01", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "g02", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "g03", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "g04", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "g05", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "g06", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "g07", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "g08", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "g09", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "g10", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "g11", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "g12", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 
]

export {stock_garden};