const stock_bathroom = [
    {
        id: "b01", 
        nombre: "Ganchos para cortina de Baño",
        sector: "Bathroom", 
        categoria: "Bañadera",
        descripcion: "Ganchos para colgar la cortina de baño" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 2200, 
        img: "../../../images/productos/producto02ganchitos.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "b02", 
        nombre: "Alfombra de microfigra para Baño",
        sector: "Bathroom", 
        categoria: "Bañadera",
        descripcion: "Alfombra de baño para la salidad de la ducha" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 4400, 
        img: "../../../images/productos/producto06alfombrabath.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "b03", 
        nombre: "Juego de Toalla y Toallon de Algodón",
        sector: "Bathroom", 
        categoria: "Bañadera",
        descripcion: "Juego de Toalla y Toallón de Algodon en Color Rojo" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 10100, 
        img: "../../../images/productos/producto30toallonrojo.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "b04", 
        nombre: "Toallón con Mochila de Boca Juniors",
        sector: "Bathroom", 
        categoria: "Bañadera",
        descripcion: "Calidad y secado del mejor toallón del mundo" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 15500, 
        img: "../../../images/productos/producto34toallonboca.jpeg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "b05", 
        nombre: "Ganchos para cortina de Baño",
        sector: "Bathroom", 
        categoria: "Bañadera",
        descripcion: "Ganchos para colgar la cortina de baño" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 2200, 
        img: "../../../images/productos/producto02ganchitos.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "b06", 
        nombre: "Alfombra de microfigra para Baño",
        sector: "Bathroom", 
        categoria: "Bañadera",
        descripcion: "Alfombra de baño para la salidad de la ducha" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 4400, 
        img: "../../../images/productos/producto06alfombrabath.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "b07", 
        nombre: "Juego de Toalla y Toallon de Algodón",
        sector: "Bathroom", 
        categoria: "Bañadera",
        descripcion: "Juego de Toalla y Toallón de Algodon en Color Rojo" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 10100, 
        img: "../../../images/productos/producto30toallonrojo.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "b08", 
        nombre: "Toallón con Mochila de Boca Juniors",
        sector: "Bathroom", 
        categoria: "Bañadera",
        descripcion: "Calidad y secado del mejor toallón del mundo" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 15500, 
        img: "../../../images/productos/producto34toallonboca.jpeg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "b09", 
        nombre: "Ganchos para cortina de Baño",
        sector: "Bathroom", 
        categoria: "Bañadera",
        descripcion: "Ganchos para colgar la cortina de baño" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 2200, 
        img: "../../../images/productos/producto02ganchitos.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "b10", 
        nombre: "Alfombra de microfigra para Baño",
        sector: "Bathroom", 
        categoria: "Bañadera",
        descripcion: "Alfombra de baño para la salidad de la ducha" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 4400, 
        img: "../../../images/productos/producto06alfombrabath.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "b11", 
        nombre: "Juego de Toalla y Toallon de Algodón",
        sector: "Bathroom", 
        categoria: "Bañadera",
        descripcion: "Juego de Toalla y Toallón de Algodon en Color Rojo" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 10100, 
        img: "../../../images/productos/producto30toallonrojo.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "b12", 
        nombre: "Toallón con Mochila de Boca Juniors",
        sector: "Bathroom", 
        categoria: "Bañadera",
        descripcion: "Calidad y secado del mejor toallón del mundo" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 15500, 
        img: "../../../images/productos/producto34toallonboca.jpeg",
        cantidad: 1,
        stock: 12, 
    }, 
]

export {stock_bathroom};