const stock_bedroom = [
    {
        id: "br01", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "br02", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "br03", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "br04", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "br05", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "br06", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "br07", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "br08", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "br09", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "br10", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "br11", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "br12", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 
]

export {stock_bedroom};