const stock_laundry = [
    {
        id: "l01", 
        nombre: "Canasto de Tela y Madera",
        sector: "Lavanderia", 
        categoria: "Accesorios Lavanderia",
        descripcion: "Receptáculo para guardar productos de limpieza y aseo" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 4554, 
        img: "../../images/productos/producto28necessairebath.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "l02", 
        nombre: "Alfombra circular de microfibra",
        sector: "Lavanderia", 
        categoria: "Alfombras",
        descripcion: "Alfombra circular de microfibra" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 2552, 
        img: "../../images/productos/producto32alfombrabathcircl.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "l03", 
        nombre: "Ganchos para colgar la ropa",
        sector: "Jardin y Exterior", 
        categoria: "Accesorios",
        descripcion: "Ganchos de madera clásicos para sujetar la ropa" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 1313, 
        img: "../../images/productos/producto36ganchos.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "l04", 
        nombre: "Ganchos para cortinas",
        sector: "Lavanderia", 
        categoria: "Accesorios Varios",
        descripcion: "Ganchos metalicos para cortinas - Decoracion" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 3553, 
        img: "../../images/productos/producto20ganchoducha.jpg", 
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "l05", 
        nombre: "Canasto de Tela y Madera",
        sector: "Lavanderia", 
        categoria: "Accesorios Lavanderia",
        descripcion: "Receptáculo para guardar productos de limpieza y aseo" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 4554, 
        img: "../../images/productos/producto28necessairebath.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "l06", 
        nombre: "Alfombra circular de microfibra",
        sector: "Lavanderia", 
        categoria: "Alfombras",
        descripcion: "Alfombra circular de microfibra" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 2552, 
        img: "../../images/productos/producto32alfombrabathcircl.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "l07", 
        nombre: "Ganchos para colgar la ropa",
        sector: "Jardin y Exterior", 
        categoria: "Accesorios",
        descripcion: "Ganchos de madera clásicos para sujetar la ropa" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 1313, 
        img: "../../images/productos/producto36ganchos.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "l08", 
        nombre: "Ganchos para cortinas",
        sector: "Lavanderia", 
        categoria: "Accesorios Varios",
        descripcion: "Ganchos metalicos para cortinas - Decoracion" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 3553, 
        img: "../../images/productos/producto20ganchoducha.jpg", 
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "l09", 
        nombre: "Canasto de Tela y Madera",
        sector: "Lavanderia", 
        categoria: "Accesorios Lavanderia",
        descripcion: "Receptáculo para guardar productos de limpieza y aseo" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 4554, 
        img: "../../images/productos/producto28necessairebath.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "l10", 
        nombre: "Alfombra circular de microfibra",
        sector: "Lavanderia", 
        categoria: "Alfombras",
        descripcion: "Alfombra circular de microfibra" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 2552, 
        img: "../../images/productos/producto32alfombrabathcircl.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "l11", 
        nombre: "Ganchos para colgar la ropa",
        sector: "Jardin y Exterior", 
        categoria: "Accesorios",
        descripcion: "Ganchos de madera clásicos para sujetar la ropa" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 1313, 
        img: "../../images/productos/producto36ganchos.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "l12", 
        nombre: "Ganchos para cortinas",
        sector: "Lavanderia", 
        categoria: "Accesorios Varios",
        descripcion: "Ganchos metalicos para cortinas - Decoracion" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 3553, 
        img: "../../images/productos/producto20ganchoducha.jpg", 
        cantidad: 1,
        stock: 12, 
    }, 

]

export {stock_laundry};