const stock_garden = [
    {
        id: "g01", 
        nombre: "Ganchos para colgar la ropa",
        sector: "Jardin y Exterior", 
        categoria: "Accesorios",
        descripcion: "Ganchos de madera clásicos para sujetar la ropa" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 1313, 
        img: "../../images/productos/producto36ganchos.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "g02", 
        nombre: "Juego de Mesas y Sillas de Jardín",
        sector: "Jardin y Exterior", 
        categoria: "Mesas y Sillas",
        descripcion: "Juego de Mesa y Sillas de Jardín de Hierro" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 43430, 
        img: "../../images/productos/producto35garden.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "g03", 
        nombre: "Canasto Deco",
        sector: "Jardin y Exterior", 
        categoria: "Accesorios Decoracion",
        descripcion: "Bandeja de mimbre ideal para decorar tu mesa de jardín" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5252, 
        img: "../../images/productos/producto29decocanasto.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "g04", 
        nombre: "Toalla y Toallón Playero",
        sector: "Jardin y Exterior", 
        categoria: "Toallones",
        descripcion: "Juego de Toalla y Toallón para su uso fuera de casa" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 7171, 
        img: "../../images/productos/producto33toallaytoallon.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "g05", 
        nombre: "Ganchos para colgar la ropa",
        sector: "Jardin y Exterior", 
        categoria: "Accesorios",
        descripcion: "Ganchos de madera clásicos para sujetar la ropa en el tender" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 1313, 
        img: "../../images/productos/producto36ganchos.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "g06", 
        nombre: "Juego de Mesas y Sillas de Jardín",
        sector: "Jardin y Exterior", 
        categoria: "Mesas y Sillas",
        descripcion: "Juego de Mesa y Sillas de Jardín de Hierro" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 43430, 
        img: "../../images/productos/producto35garden.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "g07", 
        nombre: "Canasto Deco",
        sector: "Jardin y Exterior", 
        categoria: "Accesorios Decoracion",
        descripcion: "Bandeja de mimbre ideal para decorar tu mesa de jardín" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5252, 
        img: "../../images/productos/producto29decocanasto.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "g08", 
        nombre: "Toalla y Toallón Playero",
        sector: "Jardin y Exterior", 
        categoria: "Toallones",
        descripcion: "Juego de Toalla y Toallón para su uso fuera de casa" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 7171, 
        img: "../../images/productos/producto33toallaytoallon.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "g09", 
        nombre: "Ganchos para colgar la ropa",
        sector: "Jardin y Exterior", 
        categoria: "Accesorios",
        descripcion: "Ganchos de madera clásicos para sujetar la ropa en el tender" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 1313, 
        img: "../../images/productos/producto36ganchos.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "g10", 
        nombre: "Juego de Mesas y Sillas de Jardín",
        sector: "Jardin y Exterior", 
        categoria: "Mesas y Sillas",
        descripcion: "Juego de Mesa y Sillas de Jardín de Hierro" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 43430, 
        img: "../../images/productos/producto35garden.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "g11", 
        nombre: "Canasto Deco",
        sector: "Jardin y Exterior", 
        categoria: "Accesorios Decoracion",
        descripcion: "Bandeja de mimbre ideal para decorar tu mesa de jardín" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5252, 
        img: "../../images/productos/producto29decocanasto.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "g12", 
        nombre: "Toalla y Toallón Playero",
        sector: "Jardin y Exterior", 
        categoria: "Toallones",
        descripcion: "Juego de Toalla y Toallón para su uso fuera de casa" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 7171, 
        img: "../../images/productos/producto33toallaytoallon.jpg",
        cantidad: 1,
        stock: 12, 
    }, 
]

export {stock_garden};