const stock_living = [
    {
        id: "lr01", 
        nombre: "Sillon Individual Nordico",
        sector: "Living", 
        categoria: "Sillones",
        descripcion: "Sillon Individual Nordico con 2 Almohadones de Regalo" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 47899, 
        img: "../../images/house-2563911_1280.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "lr02", 
        nombre: "Poltrona Individual",
        sector: "Living", 
        categoria: "Sillones",
        descripcion: "Poltrona Individual de Madera con 3 Almohadones" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 59990, 
        img: "../../images/productos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "lr03", 
        nombre: "Sillón de Dos Cuerpos",
        sector: "Living", 
        categoria: "Sillones",
        descripcion: "Sillon de Dos Cuerpos con Ocho Almohadones" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 142328, 
        img: "../../images/productos/producto11sillon.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "lr04", 
        nombre: "Sillon Individual Nordico",
        sector: "Living", 
        categoria: "Sillones",
        descripcion: "Sillón Individual Nordico - El par unicamente por pedido" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 257147, 
        img: "../../images/interior-design-3564955_1280.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "lr05", 
        nombre: "Sillon Individual Nordico",
        sector: "Living", 
        categoria: "Sillones",
        descripcion: "Sillon Individual Nordico con 2 Almohadones de Regalo" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 47899, 
        img: "../../images/house-2563911_1280.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "lr06", 
        nombre: "Poltrona Individual",
        sector: "Living", 
        categoria: "Sillones",
        descripcion: "Poltrona Individual de Madera con 3 Almohadones" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 59990, 
        img: "../../images/productos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "lr07", 
        nombre: "Sillón de Dos Cuerpos",
        sector: "Living", 
        categoria: "Sillones",
        descripcion: "Sillon de Dos Cuerpos con Ocho Almohadones" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 142328, 
        img: "../../images/productos/producto11sillon.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "lr08", 
        nombre: "Sillon Individual Nordico",
        sector: "Living", 
        categoria: "Sillones",
        descripcion: "Sillón Individual Nordico - El par unicamente por pedido" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 257147, 
        img: "../../images/interior-design-3564955_1280.jpg",
        cantidad: 1,
        stock: 12, 
    },

    {
        id: "lr09", 
        nombre: "Sillon Individual Nordico",
        sector: "Living", 
        categoria: "Sillones",
        descripcion: "Sillon Individual Nordico con 2 Almohadones de Regalo" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 47899, 
        img: "../../images/house-2563911_1280.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "lr10", 
        nombre: "Poltrona Individual",
        sector: "Living", 
        categoria: "Sillones",
        descripcion: "Poltrona Individual de Madera con 3 Almohadones" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 59990, 
        img: "../../images/productos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "lr11", 
        nombre: "Sillón de Dos Cuerpos",
        sector: "Living", 
        categoria: "Sillones",
        descripcion: "Sillon de Dos Cuerpos con Ocho Almohadones" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 142328, 
        img: "../../images/productos/producto11sillon.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "lr12", 
        nombre: "Sillon Individual Nordico",
        sector: "Living", 
        categoria: "Sillones",
        descripcion: "Sillón Individual Nordico - El par unicamente por pedido" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 257147, 
        img: "../../images/interior-design-3564955_1280.jpg",
        cantidad: 1,
        stock: 12, 
    },

]

export {stock_living};