const stock_laundry = [
    {
        id: "l01", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "l02", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "l03", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "l04", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "l05", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "l06", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "l07", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "l08", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "l09", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "l10", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "l11", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 

    {
        id: "l12", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: "../../pages/sectoresproductos/producto12poltrona.jpg",
        cantidad: 1,
        stock: 9, 
    }, 
]

export {stock_laundry};