const stock_bedroom = [
    {
        id: "br01", 
        nombre: "Juego de Sabanas 180 hilos",
        sector: "Dormitorio", 
        categoria: "Sabanas",
        descripcion: "Juego de Sábanas 180 hilos Percal Puro Algodon" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 12313, 
        img: "../../images/productos/producto27blancoblanco.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "br02", 
        nombre: "Manta Polar",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Una manta de polar con simil corderito en color gris" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 17717, 
        img: "../../images/productos/producto24mantapolar.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "br03", 
        nombre: "Cubresommier de raso",
        sector: "Dormitorio", 
        categoria: "Cubresommier",
        descripcion: "Cubresommier de raso blanco para cama King" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 7415, 
        img: "../../images/productos/producto31cubresommier.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "br04", 
        nombre: "Almohadas de Bellón",
        sector: "Dormitorio", 
        categoria: "Almohadas",
        descripcion: "Almohadas y almohadones de Bellon" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 4997, 
        img: "../../images/productos/producto01almohadas.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "br05", 
        nombre: "Juego de Sabanas 180 hilos",
        sector: "Dormitorio", 
        categoria: "Sabanas",
        descripcion: "Juego de Sábanas 180 hilos Percal Puro Algodon" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 12313, 
        img: "../../images/productos/producto27blancoblanco.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "br06", 
        nombre: "Manta Polar",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Una manta de polar con simil corderito en color gris" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 17717, 
        img: "../../images/productos/producto24mantapolar.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "br07", 
        nombre: "Cubresommier de raso",
        sector: "Dormitorio", 
        categoria: "Cubresommier",
        descripcion: "Cubresommier de raso blanco para cama King" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 7415, 
        img: "../../images/productos/producto31cubresommier.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "br08", 
        nombre: "Almohadas de Bellón",
        sector: "Dormitorio", 
        categoria: "Almohadas",
        descripcion: "Almohadas y almohadones de Bellon" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 4997, 
        img: "../../images/productos/producto01almohadas.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "br09", 
        nombre: "Juego de Sabanas 180 hilos",
        sector: "Dormitorio", 
        categoria: "Sabanas",
        descripcion: "Juego de Sábanas 180 hilos Percal Puro Algodon" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 12313, 
        img: "../../images/productos/producto27blancoblanco.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "br10", 
        nombre: "Manta Polar",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Una manta de polar con simil corderito en color gris" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 17717, 
        img: "../../images/productos/producto24mantapolar.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "br11", 
        nombre: "Cubresommier de raso",
        sector: "Dormitorio", 
        categoria: "Cubresommier",
        descripcion: "Cubresommier de raso blanco para cama King" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 7415, 
        img: "../../images/productos/producto31cubresommier.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

    {
        id: "br12", 
        nombre: "Almohadas de Bellón",
        sector: "Dormitorio", 
        categoria: "Almohadas",
        descripcion: "Almohadas y almohadones de Bellon" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 4997, 
        img: "../../images/productos/producto01almohadas.jpg",
        cantidad: 1,
        stock: 12, 
    }, 

]

export {stock_bedroom};
