const stockdormitorio = [
    {
        id: "D1", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad: 9, 
    }, 

    {
        id: "D2", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad:6, 
    }, 
    {
        id: "D3", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad: 1, 
    }, 
    {
        id: "D4", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad: 3, 
    }, 
    {
        id: "D5", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Acolchados",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad: 5, 
    }, 
    {
        id: "D6", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Acolchados",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad:3, 
    }, 
    {
        id: "D7", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Acolchados",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad: 3, 
    }, 
    {
        id: "D8", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Acolchados",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad: 29, 
    }, 
    {
        id: "D9", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Acolchados",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad:1, 
    }, 
    {
        id: "D10", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad:1, 
    }, 
    {
        id: "D11", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad: 2, 
    }, 
    {
        id: "D12", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad: 8, 
    }, 
    {
        id: "D13", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad: 2, 
    }, 
    {
        id: "D14", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad: 1, 
    }, 
    {
        id: "D15", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad:3, 
    }, 
    {
        id: "D16", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad: 4, 
    }, 
    {
        id: "D71", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad:3, 
    }, 
    {
        id: "D18", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad: 2, 
    }, 
    {
        id: "D19", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad:4, 
    }, 
    {
        id: "D20", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad:4, 
    }, 
    {
        id: "D21", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad:3, 
    }, 
    {
        id: "D22", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad: 49, 
    }, 
    {
        id: "D23", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad:2, 
    }, 
    {
        id: "D24", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad: 12, 
    }, 
    {
        id: "D25", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad:15, 
    }, 
    {
        id: "D26", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad: 11, 
    }, 
    {
        id: "D27", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad: 9, 
    }, 
    {
        id: "D28", 
        nombre: "Frazada Microfibra Lisa",
        sector: "Dormitorio", 
        categoria: "Frazadas",
        descripcion: "Un sillon ideal para completar tu juego de living" , 
        marca: "Lantermo",
        size: "1 1/2 Plazas", 
        precio: 5147.34, 
        img: 'producto12poltrona.jpg',
        cantidad: 19, 
    }, 
]

const compra = (id) => { 
    console.log (`hizo click en el producto con id: ${id}`)
    Swal.fire({
        title: 'Añadido Exitosamente',
        text: 'Su producto ya se encuentra añadido al carrito!',
        icon: 'success',
        confirmButtonText: 'Continuar'})  
}

//Creacion de las cards de Productos
const mostrarProductos = (stockdormitorio) =>{
    const contenedor = document.getElementById ('dormitoriomain');
        stockdormitorio.forEach( (stockdormitorio) => {
            const div = document.createElement ('div');
            div.classList.add ('card')
            div.innerHTML +=  ` <div class="card-image">
                                <img src=${stockdormitorio.img} style= width:100%>
                                <span class= "card-title">${stockdormitorio.nombre}</span><br>
                                </div>
                                <div>
                                <p>${stockdormitorio.descripcion}</p>
                                <p>${stockdormitorio.precio}</p>
                                <a class="btn btn-primary" href="#${stockdormitorio.id}" id=boton style= float:right>Comprar</a>
                                </div>
            `;
            div.onclick = () => compra (stockdormitorio.id);
            contenedor.appendChild(div);   
        });
}; 

mostrarProductos (stockdormitorio)


fetch ('https://api.mercadopago.com')
.then ((resp) => resp.json())
.then ((data) => {
    console.log (data)
})